<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Exp extends CI_Controller {
	public $em;
	function __construct(){
		parent::__construct();
		$this->load->model('ModelExperiencia');
		$this->em = $this->doctrine->em;
	}
	public function index(){

	}
	public function add(){
		$data = array(
			'idiomas' => $this->getCatalogo('idiomas',TRUE),
			'husosHorarios' => $this->getCatalogo('husosHorarios',TRUE),
			'moneda' => $this->getCatalogo('moneda',TRUE)
			);
		// print_r($this->getCatalogo('idiomas',TRUE));
		$this->load->view('formExperiencia',$data);
	}
	public function getCatalogo($catalogo = 0,$r = FALSE){
		if($r === FALSE){
			if($catalogo == 0)
			$this->output->set_content_type('application/json')->set_output(json_encode(array('code'=>500,'msg'=>'Error Catalogo no exite')));
			switch ($catalogo) {
				case 'idiomas':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'code'=>200,
								'msg'=>array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
									)
								)
							)
						);
					
					break;
				case 'husosHorarios':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'code'=>200,
								'msg'=>array(
								'UTC - Hora universal coordinada - GMT',
								'ECT - Hora de Europa central - GMT+1:00',
								'EET - Hora de Europa oriental - GMT+2:00',
								'ART - Hora oficial de Egipto (Árabe) - GMT+2:00',
								'EAT - Hora de África oriental - GMT+3:00',
								'MET - Hora de Oriente Medio - GMT+3:30',
								'NET - Hora de Próximo Oriente - GMT+4:00',
								'PLT - Hora de Lahore, Pakistán - GMT+5:00',
								'IST - Hora oficial de la India - GMT+5:30',
								'BST - Hora oficial de Bangladesh - GMT+6:00',
								'VST - Hora oficial de Vietnam - GMT+7:00',
								'CTT - Hora de China / Taiwán - GMT+8:00',
								'JST - Hora oficial de Japón - GMT+9:00',
								'ACT - Hora de Australia (Centro) - GMT+9:30',
								'AET - Hora de Australia (Este) - GMT+10:00',
								'SST - Hora oficial de las Islas Salomón - GMT+11:00',
								'NST - Hora oficial de Nueva Zelanda - GMT+12:00',
								'MIT - Hora de las Islas Midway - GMT-11:00',
								'HST - Hora oficial de Hawaii - GMT-10:00',
								'AST - Hora oficial de Alaska - GMT-9:00',
								'PST - Hora oficial del Pacífico - GMT-8:00',
								'PNT - Hora oficial de Phoenix - GMT-7:00',
								'MST - Hora oficial de las Montañas Rocosas - GMT-7:00',
								'CST - Hora oficial central (EEUU y Canadá) - GMT-6:00',
								'EST - Hora oficial del Este de EE.UU. - GMT-5:00',
								'IET - Hora oficial de Indiana (Este) - GMT-5:00',
								'PRT - Hora de Puerto Rico e Islas Vírgenes de EEUU - GMT-4:00',
								'CNT - Hora de Terranova (Canadá) - GMT-3:30',
								'AGT - Hora oficial de Argentina - GMT-3:00',
								'BET - Hora de Brasil (Este) - GMT-3:00',
								'CAT - Hora de África central - GMT-1:00'
								)
								)
							)
						);
					break;
				case 'moneda':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'code'=>200,
								'msg'=>array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
									)
								)
							)
						);
					break;
				default:
					$this->output->set_content_type('application/json')->set_output(json_encode(array('code'=>500,'msg'=>'Error Catalogo no exite')));
					break;
			}
		}else{
			// echo $catalogo;
			// if($catalogo == 0)
			// 	return array();
			switch ($catalogo) {
				case 'idiomas':
					return array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
						);
				case 'husosHorarios':
					return array(
								'UTC - Hora universal coordinada - GMT',
								'ECT - Hora de Europa central - GMT+1:00',
								'EET - Hora de Europa oriental - GMT+2:00',
								'ART - Hora oficial de Egipto (Árabe) - GMT+2:00',
								'EAT - Hora de África oriental - GMT+3:00',
								'MET - Hora de Oriente Medio - GMT+3:30',
								'NET - Hora de Próximo Oriente - GMT+4:00',
								'PLT - Hora de Lahore, Pakistán - GMT+5:00',
								'IST - Hora oficial de la India - GMT+5:30',
								'BST - Hora oficial de Bangladesh - GMT+6:00',
								'VST - Hora oficial de Vietnam - GMT+7:00',
								'CTT - Hora de China / Taiwán - GMT+8:00',
								'JST - Hora oficial de Japón - GMT+9:00',
								'ACT - Hora de Australia (Centro) - GMT+9:30',
								'AET - Hora de Australia (Este) - GMT+10:00',
								'SST - Hora oficial de las Islas Salomón - GMT+11:00',
								'NST - Hora oficial de Nueva Zelanda - GMT+12:00',
								'MIT - Hora de las Islas Midway - GMT-11:00',
								'HST - Hora oficial de Hawaii - GMT-10:00',
								'AST - Hora oficial de Alaska - GMT-9:00',
								'PST - Hora oficial del Pacífico - GMT-8:00',
								'PNT - Hora oficial de Phoenix - GMT-7:00',
								'MST - Hora oficial de las Montañas Rocosas - GMT-7:00',
								'CST - Hora oficial central (EEUU y Canadá) - GMT-6:00',
								'EST - Hora oficial del Este de EE.UU. - GMT-5:00',
								'IET - Hora oficial de Indiana (Este) - GMT-5:00',
								'PRT - Hora de Puerto Rico e Islas Vírgenes de EEUU - GMT-4:00',
								'CNT - Hora de Terranova (Canadá) - GMT-3:30',
								'AGT - Hora oficial de Argentina - GMT-3:00',
								'BET - Hora de Brasil (Este) - GMT-3:00',
								'CAT - Hora de África central - GMT-1:00'
						);
				case 'moneda':
					array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
						);
				default:
					return array();
					break;
			}
		}
	}
}
