<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Exp extends CI_Controller {
	public $em;
	function __construct(){
		parent::__construct();
		$this->load->model('ModelExperiencia');
		$this->em = $this->doctrine->em;
	}

	public function index(){
		$data = array('exp'=> $this->em->getRepository('Experiencia')->findAll() );
		$this->load->view('allExp',$data);
	}
	public function borrar($id){
		$exp = $this->em->getRepository('Experiencia')->findOneBy(array('idexperiencia'=>$id));
		$this->em->remove($exp);
    	$this->em->flush();
		redirect('admin');
	}
	public function add(){
		$data = array(
			'idiomas' => $this->getCatalogo('idiomas',TRUE),
			'husosHorarios' => $this->getCatalogo('husosHorarios',TRUE),
			'moneda' => $this->getCatalogo('moneda',TRUE),
			'religion' => $this->getCatalogo('religion',TRUE)
			);
		// print_r($this->getCatalogo('idiomas',TRUE));
		$this->load->view('formExperiencia',$data);
	}
	public function getCatalogo($catalogo = 0,$r = FALSE){
		if($r === FALSE){
			if($catalogo == 0)
			$this->output->set_content_type('application/json')->set_output(json_encode(array('code'=>500,'msg'=>'Error Catalogo no exite')));
			switch ($catalogo) {
				case 'religion':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'Cristianismo',
								'Islam',
								'Secular / No religiosos / Agnóstico / Ateo',
								'Hinduismo',
								'Religión tradicional china',
								'Budismo',
								'primal-indígenas',
								'Tradicional africana y la diáspora',
								'Sijismo',
								'Juche',
								'Espiritismo',
								'Judaísmo',
								'Baha\'i',
								'Jainismo',
								'Sintoísta',
								'Cao Dai',
								'Zoroastrismo',
								'Tenrikyo',
								'Neo-Paganismo',
								'Unitarismo Universalista',
								'Scientology'
								)
							)
						);
					break;
				case 'idiomas':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'code'=>200,
								'msg'=>array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
									)
								)
							)
						);
					
					break;
				case 'husosHorarios':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
								'code'=>200,
								'msg'=>array(
								'UTC - Hora universal coordinada - GMT',
								'ECT - Hora de Europa central - GMT+1:00',
								'EET - Hora de Europa oriental - GMT+2:00',
								'ART - Hora oficial de Egipto (Árabe) - GMT+2:00',
								'EAT - Hora de África oriental - GMT+3:00',
								'MET - Hora de Oriente Medio - GMT+3:30',
								'NET - Hora de Próximo Oriente - GMT+4:00',
								'PLT - Hora de Lahore, Pakistán - GMT+5:00',
								'IST - Hora oficial de la India - GMT+5:30',
								'BST - Hora oficial de Bangladesh - GMT+6:00',
								'VST - Hora oficial de Vietnam - GMT+7:00',
								'CTT - Hora de China / Taiwán - GMT+8:00',
								'JST - Hora oficial de Japón - GMT+9:00',
								'ACT - Hora de Australia (Centro) - GMT+9:30',
								'AET - Hora de Australia (Este) - GMT+10:00',
								'SST - Hora oficial de las Islas Salomón - GMT+11:00',
								'NST - Hora oficial de Nueva Zelanda - GMT+12:00',
								'MIT - Hora de las Islas Midway - GMT-11:00',
								'HST - Hora oficial de Hawaii - GMT-10:00',
								'AST - Hora oficial de Alaska - GMT-9:00',
								'PST - Hora oficial del Pacífico - GMT-8:00',
								'PNT - Hora oficial de Phoenix - GMT-7:00',
								'MST - Hora oficial de las Montañas Rocosas - GMT-7:00',
								'CST - Hora oficial central (EEUU y Canadá) - GMT-6:00',
								'EST - Hora oficial del Este de EE.UU. - GMT-5:00',
								'IET - Hora oficial de Indiana (Este) - GMT-5:00',
								'PRT - Hora de Puerto Rico e Islas Vírgenes de EEUU - GMT-4:00',
								'CNT - Hora de Terranova (Canadá) - GMT-3:30',
								'AGT - Hora oficial de Argentina - GMT-3:00',
								'BET - Hora de Brasil (Este) - GMT-3:00',
								'CAT - Hora de África central - GMT-1:00'
								)
								)
							)
						);
					break;
				case 'moneda':
					$this->output->set_content_type('application/json')->set_output(
						json_encode(
							array(
							'Lek',
							'Euro',
							'Dram',
							'Manat',
							'Rublo Bielorruso',
							'Marco Convertible',
							'Lev',
							'Libra de Chipre',
							'Kuna',
							'Corona Danesa',
							'Corona Eslovaca',
							'Tolar',
							'Corona de Estonia',
							'Forintio',
							'Corona islandesa',
							'Tengue',
							'Som',
							'Lat',
							'Franco Suizo',
							'Lit',
							'Libra Maltesa',
							'Leu de Moldova',
							'Corona noruega',
							'Zloty',
							'Libra esterlina',
							'Corona Checa',
							'Leu',
							'Rublo',
							'Corona sueca',
							'Grivna',
							'Som-kupon',
							'Nuevo dinar',
							'Florín de las Antillas',
							'Peso Argentino',
							'Dólar de las Bahamas',
							'Dólar de Barbados',
							'Dólar de Belice',
							'Peso Boliviano',
							'Real',
							'Dólar de Canadá',
							'Peso Chileno',
							'Peso Colombiano',
							'Colon de Costa Rica',
							'Peso Cubano',
							'Dólar USA',
							'Colón del Salvador',
							'Dólar del Caribe Oriental',
							'Quetzal',
							'Franco francés',
							'Dólar de Guyana',
							'Gourde-Dólar USA',
							'Lempira',
							'Dólar de las Islas Caimán',
							'Dólar de Jamaica',
							'Peso mexicano',
							'Córdoba',
							'Dólar USA / Balboa',
							'Guaraní',
							'Sol',
							'Peso Dominicano',
							'Florín de Surinam',
							'Dólar de Trinidad y Tobago',
							'Peso Uruguayo',
							'Bolívar',
							'Afgani',
							'Rial Saudita',
							'Dinar Bahraini',
							'Taka',
							'Rupia hindú',
							'Dólar de Brunei',
							'Riel',
							'Yuan Renminbi',
							'Won norcoreano',
							'Won',
							'Dirham UAE',
							'Peso filipino',
							'Rupia',
							'Dinar Iraquí',
							'Rial Iraní',
							'Shekel',
							'Yen',
							'Dinar jordano',
							'Dinar Kuwaití',
							'Kip',
							'Libra libanesa',
							'Ringgit Malaysio',
							'Rupia de las Maldivas',
							'Tugrik',
							'Kyat de Myanmar',
							'Rupia nepali',
							'Rial Omani',
							'Rupia Paquistaní',
							'Rial Qatari',
							'Dólar de Singapur',
							'Libra Siria',
							'Rupia de Sri Lanka',
							'Baht',
							'Dólar de Taiwán',
							'Dong',
							'Rial de Yemen',
							'Kwanza',
							'Dinar argelino',
							'Franco CFA',
							'Pula',
							'Franco de Burundi',
							'Escudo de Cabo Verde',
							'Franco de las Comores',
							'Franco de Djibouti',
							'Libra egipcia',
							'Biir etiope',
							'Dalasi',
							'Cedi',
							'Syli',
							'Peso de Guinea Bissau',
							'Ekwele',
							'Chelín keniata',
							'Maloti-Rand',
							'Dólar de Liberia',
							'Dinar Libio (Jamahiriya Arabe)',
							'Franco malgache',
							'Kwacha',
							'Franco de Mali',
							'Dirham marroquí',
							'Rupia de las Mauricio',
							'Ouguiya',
							'Metical',
							'Rand',
							'Naira',
							'Franco de Ruanda',
							'Rupia de las Seychelles',
							'Leone',
							'Chelín Somali',
							'Lilangeni',
							'Libra Sudanes',
							'Chelín Tanzano',
							'Dinar tunecino',
							'Chelín de Uganda',
							'Dólar de Zimbabwe',
							'Dólar Australiano',
							'Dólar de Fitji',
							'Dólar de las Islas Salomón',
							'Dólar de Nueva Zelanda',
							'Kina',
							'Vatu'
							)
						)
					);
					break;
				default:
					$this->output->set_content_type('application/json')->set_output(json_encode(array('code'=>500,'msg'=>'Error Catalogo no exite')));
					break;
			}
		}else{
			// echo $catalogo;
			// if($catalogo == 0)
			// 	return array();
			switch ($catalogo) {
				case 'religion':
					return array(
								'Cristianismo',
								'Islam',
								'Secular / No religiosos / Agnóstico / Ateo',
								'Hinduismo',
								'Religión tradicional china',
								'Budismo',
								'primal-indígenas',
								'Tradicional africana y la diáspora',
								'Sijismo',
								'Juche',
								'Espiritismo',
								'Judaísmo',
								'Baha\'i',
								'Jainismo',
								'Sintoísta',
								'Cao Dai',
								'Zoroastrismo',
								'Tenrikyo',
								'Neo-Paganismo',
								'Unitarismo Universalista',
								'Scientology'
						);
				case 'idiomas':
					return array(
									'pastún',
									'persa',
									'albanés',
									'alemán',
									'catalán',
									'portugués',
									'inglés',
									'árabe',
									'armenio',
									'azerí',
									'bengalí',
									'francés',
									'neerlandés',
									'bielorruso',
									'ruso',
									'birmano',
									'castellano',
									'aymara',
									'araona',
									'baure',
									'bésiro',
									'canichana',
									'cavineño',
									'cayubaba',
									'chácobo',
									'chimán',
									'ese ejja',
									'guaraní',
									'guarasu’we',
									'guarayu',
									'itonama',
									'leco',
									'machajuyai-kallawaya',
									'machineri',
									'maropa',
									'mojeño-trinitario',
									'mojeño-ignaciano',
									'moré',
									'mosetén',
									'movima',
									'pacawara',
									'puquina',
									'quechua',
									'sirionó',
									'tacana',
									'tapiete',
									'toromona',
									'uru-chipaya',
									'weenhayek',
									'yaminawa',
									'yuki',
									'yuracaré',
									'zamuco',
									'bosnio',
									'croata',
									'serbio',
									'malayo',
									'búlgaro',
									'rundi',
									'dzongka',
									'jemer',
									'cingalés',
									'tamil',
									'griego',
									'turco',
									'italiano',
									'latín',
									'español',
									'comorense',
									'coreano',
									'danés',
									'tigriña',
									'eslovaco',
									'esloveno',
									'lengua de signos española ',
									'estonio',
									'amárico',
									'filipino',
									'finés¹',
									'sueco²',
									'indostano fiyiano',
									'fiyiano',
									'georgiano',
									'criollo haitiano',
									'húngaro',
									'hindi',
									'indonesio',
									'irlandés',
									'islandés',
									'hebreo',
									'japonés',
									'kazajo',
									'suahili',
									'kirguís',
									'kiribatiano',
									'lao',
									'soto meridional',
									'letón',
									'lituano',
									'alemán',
									'luxemburgués',
									'macedonio',
									'malgache',
									'chicheua',
									'maldivo',
									'maltés',
									'marshalés',
									'moldavo',
									'mongol',
									'nauruano',
									'nepalí',
									'noruego',
									'Lengua de Signos Neozelandesa',
									'maorí',
									'urdu',
									'palaosiano',
									'hiri motu',
									'tok pisin',
									'aimara',
									'Jaqaru',
									'Ticuna',
									'Candoshi',
									'Urarina',
									'Cauqui',
									'Culina',
									'Amuesha',
									'Asháninca',
									'Caquinte',
									'Machiguenga',
									'Chayahuita',
									'Jébero',
									'Bora',
									'Huitoto',
									'Amarakaeri',
									'Achuar',
									'Aguaruna',
									'Huambisa',
									'Capanahua',
									'Cashibo-cacataibo',
									'Cashinahua',
									'Matsés',
									'Shipibo-conibo',
									'Yagua',
									'Cocama',
									'Omagua',
									'Yine',
									'polaco',
									'checo',
									'ruanda',
									'rumano',
									'samoano',
									'criollo seychellense',
									'mandarín',
									'somalí',
									'suazi',
									'afrikáans',
									'ndebele meridional',
									'soto septentrional',
									'tsonga',
									'tsuana',
									'venda',
									'xosa',
									'zulú',
									'romanche',
									'tai',
									'tayiko',
									'tetum',
									'tongano',
									'turcomano',
									'tuvaluano',
									'ucraniano',
									'uzbeko',
									'bislama',
									'vietnamita'
						);
				case 'husosHorarios':
					return array(
								'UTC - Hora universal coordinada - GMT',
								'ECT - Hora de Europa central - GMT+1:00',
								'EET - Hora de Europa oriental - GMT+2:00',
								'ART - Hora oficial de Egipto (Árabe) - GMT+2:00',
								'EAT - Hora de África oriental - GMT+3:00',
								'MET - Hora de Oriente Medio - GMT+3:30',
								'NET - Hora de Próximo Oriente - GMT+4:00',
								'PLT - Hora de Lahore, Pakistán - GMT+5:00',
								'IST - Hora oficial de la India - GMT+5:30',
								'BST - Hora oficial de Bangladesh - GMT+6:00',
								'VST - Hora oficial de Vietnam - GMT+7:00',
								'CTT - Hora de China / Taiwán - GMT+8:00',
								'JST - Hora oficial de Japón - GMT+9:00',
								'ACT - Hora de Australia (Centro) - GMT+9:30',
								'AET - Hora de Australia (Este) - GMT+10:00',
								'SST - Hora oficial de las Islas Salomón - GMT+11:00',
								'NST - Hora oficial de Nueva Zelanda - GMT+12:00',
								'MIT - Hora de las Islas Midway - GMT-11:00',
								'HST - Hora oficial de Hawaii - GMT-10:00',
								'AST - Hora oficial de Alaska - GMT-9:00',
								'PST - Hora oficial del Pacífico - GMT-8:00',
								'PNT - Hora oficial de Phoenix - GMT-7:00',
								'MST - Hora oficial de las Montañas Rocosas - GMT-7:00',
								'CST - Hora oficial central (EEUU y Canadá) - GMT-6:00',
								'EST - Hora oficial del Este de EE.UU. - GMT-5:00',
								'IET - Hora oficial de Indiana (Este) - GMT-5:00',
								'PRT - Hora de Puerto Rico e Islas Vírgenes de EEUU - GMT-4:00',
								'CNT - Hora de Terranova (Canadá) - GMT-3:30',
								'AGT - Hora oficial de Argentina - GMT-3:00',
								'BET - Hora de Brasil (Este) - GMT-3:00',
								'CAT - Hora de África central - GMT-1:00'
						);
				case 'moneda':
					return array(
						'Lek',
						'Euro',
						'Dram',
						'Manat',
						'Rublo Bielorruso',
						'Marco Convertible',
						'Lev',
						'Libra de Chipre',
						'Kuna',
						'Corona Danesa',
						'Corona Eslovaca',
						'Tolar',
						'Corona de Estonia',
						'Forintio',
						'Corona islandesa',
						'Tengue',
						'Som',
						'Lat',
						'Franco Suizo',
						'Lit',
						'Libra Maltesa',
						'Leu de Moldova',
						'Corona noruega',
						'Zloty',
						'Libra esterlina',
						'Corona Checa',
						'Leu',
						'Rublo',
						'Corona sueca',
						'Grivna',
						'Som-kupon',
						'Nuevo dinar',
						'Florín de las Antillas',
						'Peso Argentino',
						'Dólar de las Bahamas',
						'Dólar de Barbados',
						'Dólar de Belice',
						'Peso Boliviano',
						'Real',
						'Dólar de Canadá',
						'Peso Chileno',
						'Peso Colombiano',
						'Colon de Costa Rica',
						'Peso Cubano',
						'Dólar USA',
						'Colón del Salvador',
						'Dólar del Caribe Oriental',
						'Quetzal',
						'Franco francés',
						'Dólar de Guyana',
						'Gourde-Dólar USA',
						'Lempira',
						'Dólar de las Islas Caimán',
						'Dólar de Jamaica',
						'Peso mexicano',
						'Córdoba',
						'Dólar USA / Balboa',
						'Guaraní',
						'Sol',
						'Peso Dominicano',
						'Florín de Surinam',
						'Dólar de Trinidad y Tobago',
						'Peso Uruguayo',
						'Bolívar',
						'Afgani',
						'Rial Saudita',
						'Dinar Bahraini',
						'Taka',
						'Rupia hindú',
						'Dólar de Brunei',
						'Riel',
						'Yuan Renminbi',
						'Won norcoreano',
						'Won',
						'Dirham UAE',
						'Peso filipino',
						'Rupia',
						'Dinar Iraquí',
						'Rial Iraní',
						'Shekel',
						'Yen',
						'Dinar jordano',
						'Dinar Kuwaití',
						'Kip',
						'Libra libanesa',
						'Ringgit Malaysio',
						'Rupia de las Maldivas',
						'Tugrik',
						'Kyat de Myanmar',
						'Rupia nepali',
						'Rial Omani',
						'Rupia Paquistaní',
						'Rial Qatari',
						'Dólar de Singapur',
						'Libra Siria',
						'Rupia de Sri Lanka',
						'Baht',
						'Dólar de Taiwán',
						'Dong',
						'Rial de Yemen',
						'Kwanza',
						'Dinar argelino',
						'Franco CFA',
						'Pula',
						'Franco de Burundi',
						'Escudo de Cabo Verde',
						'Franco de las Comores',
						'Franco de Djibouti',
						'Libra egipcia',
						'Biir etiope',
						'Dalasi',
						'Cedi',
						'Syli',
						'Peso de Guinea Bissau',
						'Ekwele',
						'Chelín keniata',
						'Maloti-Rand',
						'Dólar de Liberia',
						'Dinar Libio (Jamahiriya Arabe)',
						'Franco malgache',
						'Kwacha',
						'Franco de Mali',
						'Dirham marroquí',
						'Rupia de las Mauricio',
						'Ouguiya',
						'Metical',
						'Rand',
						'Naira',
						'Franco de Ruanda',
						'Rupia de las Seychelles',
						'Leone',
						'Chelín Somali',
						'Lilangeni',
						'Libra Sudanes',
						'Chelín Tanzano',
						'Dinar tunecino',
						'Chelín de Uganda',
						'Dólar de Zimbabwe',
						'Dólar Australiano',
						'Dólar de Fitji',
						'Dólar de las Islas Salomón',
						'Dólar de Nueva Zelanda',
						'Kina',
						'Vatu'
						);
				default:
					return array();
					break;
			}
		}
	}
}
